"""Tests for daydream.pr_comment_renderer.

One test per Must-Have requirement (M1–M10), plus single-phase baseline,
purity/idempotence, and the deep-mode multi-trajectory aggregation case
called out in S2.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from daydream.pr_comment_renderer import render_run_info_block

# Fixture trajectory files committed under tests/fixtures/trajectories/.
# Those small-but-realistic files cover Claude (cost_usd present) and
# Codex (cost_usd null, synthesized via pricing.compute_cost). Tests that
# need a *specific* shape (mixed-model, unknown-model, missing data) build
# their trajectory inline via _write_trajectory below.
_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "trajectories"
_SINGLE_PHASE = _FIXTURE_DIR / "single_phase_claude.json"
_MULTI_PHASE_CODEX = _FIXTURE_DIR / "multi_phase_codex.json"
_SIBLING_FIX = _FIXTURE_DIR / "sibling_fix.json"


def _agent_step(
    *,
    step_id: int,
    phase: str,
    model: str | None,
    prompt: int = 1000,
    completion: int = 100,
    cached: int = 500,
    cost_usd: float | None = None,
    tool_calls: int = 0,
) -> dict[str, Any]:
    """Build a minimal valid agent step dict for fixture construction."""
    step: dict[str, Any] = {
        "step_id": step_id,
        "timestamp": f"2026-05-02T00:00:{step_id:02d}.000000Z",
        "source": "agent",
        "message": "ok",
        "extra": {"daydream_phase": phase, "daydream_run_flow": "ttt"},
        "metrics": {
            "prompt_tokens": prompt,
            "completion_tokens": completion,
            "cached_tokens": cached,
            "cost_usd": cost_usd,
        },
    }
    if model is not None:
        step["model_name"] = model
    if tool_calls > 0:
        tcs = [
            {"tool_call_id": f"s{step_id}-t{i}", "function_name": "X", "arguments": {}}
            for i in range(tool_calls)
        ]
        step["tool_calls"] = tcs
        step["observation"] = {
            "results": [{"source_call_id": tc["tool_call_id"], "content": "ok"} for tc in tcs]
        }
    return step


def _write_trajectory(
    tmp_path: Path,
    *,
    name: str = "t.json",
    session_id: str = "fixture",
    model: str = "gpt-5.5",
    steps: list[dict[str, Any]],
) -> Path:
    """Write a trajectory dict to tmp and return the path.

    Wraps the steps with a minimal Agent block + the single user step the
    Trajectory validator expects (step_id 1 sequential).
    """
    full = {
        "schema_version": "ATIF-v1.6",
        "session_id": session_id,
        "agent": {"name": "daydream", "version": "0.14.0", "model_name": model},
        "steps": steps,
    }
    p = tmp_path / name
    p.write_text(json.dumps(full), encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# M1 — visible rollup
# ---------------------------------------------------------------------------
def test_m1_visible_rollup_includes_required_fields() -> None:
    """Rollup must list Mode, Model, Cost, Tokens, Steps/tool calls."""
    out = render_run_info_block([_SINGLE_PHASE], "trust-the-technology", "0.14.0")
    assert "- **Mode:** trust-the-technology" in out
    assert "- **Model:** claude-sonnet-4-5" in out
    assert "- **Cost:** $0.13" in out
    assert "- **Tokens:** 12,400 in" in out
    assert "- **Steps / tool calls:** 1 / 2" in out


# ---------------------------------------------------------------------------
# M2 — collapsed per-phase table
# ---------------------------------------------------------------------------
def test_m2_per_phase_breakdown_is_collapsed_table() -> None:
    """Per-phase breakdown is a markdown table inside <details>."""
    out = render_run_info_block([_MULTI_PHASE_CODEX], "deep review", "0.14.0")
    assert "<details><summary>Per-phase breakdown</summary>" in out
    assert "</details>" in out
    # Header row with all required columns.
    assert "| Phase | Model | Steps | Tools | Input | Cached | Output | Cost |" in out
    # Both phases present.
    assert "| Review |" in out
    assert "| Fix |" in out


# ---------------------------------------------------------------------------
# M3 — version footer
# ---------------------------------------------------------------------------
def test_m3_version_footer_present() -> None:
    """Footer names the daydream version that produced the comment."""
    out = render_run_info_block([_SINGLE_PHASE], "ttt", "0.14.0")
    assert "<sub>Generated by daydream v0.14.0</sub>" in out


# ---------------------------------------------------------------------------
# M4 — uniform field set across modes
# ---------------------------------------------------------------------------
def test_m4_uniform_layout_across_mode_labels() -> None:
    """Different mode labels produce the same set of section headers/columns."""
    a = render_run_info_block([_SINGLE_PHASE], "comment", "0.14.0")
    b = render_run_info_block([_SINGLE_PHASE], "feedback", "0.14.0")
    c = render_run_info_block([_SINGLE_PHASE], "deep review", "0.14.0")
    for label in ("- **Model:**", "- **Cost:**", "- **Tokens:**", "- **Steps / tool calls:**"):
        assert label in a
        assert label in b
        assert label in c
    # Same column header in all three.
    header = "| Phase | Model | Steps | Tools | Input | Cached | Output | Cost |"
    assert header in a
    assert header in b
    assert header in c


# ---------------------------------------------------------------------------
# M5 — cost source per backend
# ---------------------------------------------------------------------------
def test_m5_cost_source_per_backend(tmp_path: Path) -> None:
    """Claude steps use Metrics.cost_usd verbatim; Codex steps synthesize from pricing.

    A trajectory with one Claude step (cost_usd=0.50) and one Codex step
    on gpt-5.5 (cost_usd=None, 1M uncached input tokens at $5.00/1M) should
    sum to $5.50: 0.50 SDK + 5.00 synthesized.
    """
    p = _write_trajectory(
        tmp_path,
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="claude-sonnet-4-5",
                prompt=1000,
                completion=0,
                cached=0,
                cost_usd=0.50,
            ),
            _agent_step(
                step_id=3,
                phase="fix",
                model="gpt-5.5",
                prompt=1_000_000,
                completion=0,
                cached=0,
                cost_usd=None,
            ),
        ],
    )
    out = render_run_info_block([p], "ttt", "0.14.0")
    # 0.50 + 5.00 = 5.50
    assert "- **Cost:** $5.50" in out


# ---------------------------------------------------------------------------
# M6 — unknown-model fallback
# ---------------------------------------------------------------------------
def test_m6_unknown_model_renders_dash_and_footnote(tmp_path: Path) -> None:
    """Unknown OpenAI model: rollup '—', per-phase '—', footnote names the model."""
    p = _write_trajectory(
        tmp_path,
        model="mystery-model",
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="mystery-model",
                cost_usd=None,
            ),
        ],
    )
    out = render_run_info_block([p], "ttt", "0.14.0")
    assert "- **Cost:** —" in out
    assert "| —" in out  # per-phase cost cell ends with —
    assert "mystery-model" in out
    assert "not in the price table" in out


# ---------------------------------------------------------------------------
# M7 — mixed-model label
# ---------------------------------------------------------------------------
def test_m7_mixed_models_render_breakdown_pointer(tmp_path: Path) -> None:
    """Two phases on different models -> rollup Model = 'mixed — see breakdown'."""
    p = _write_trajectory(
        tmp_path,
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(step_id=2, phase="review", model="gpt-5.5", cost_usd=0.10),
            _agent_step(step_id=3, phase="fix", model="claude-sonnet-4-5", cost_usd=0.20),
        ],
    )
    out = render_run_info_block([p], "ttt", "0.14.0")
    assert "- **Model:** mixed — see breakdown" in out


# ---------------------------------------------------------------------------
# M8 — cached-tokens awareness in the rollup
# ---------------------------------------------------------------------------
def test_m8_cache_hit_ratio_rendered_when_input_nonzero(tmp_path: Path) -> None:
    """Cache-hit ratio is computed from (cached / input) and shown next to cached count."""
    p = _write_trajectory(
        tmp_path,
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="gpt-5.5",
                prompt=10_000,
                completion=200,
                cached=6_700,
                cost_usd=0.01,
            ),
        ],
    )
    out = render_run_info_block([p], "ttt", "0.14.0")
    # 6700 / 10000 = 67%
    assert "10,000 in (6,700 cached, 67% hit)" in out


# ---------------------------------------------------------------------------
# M9 — missing-trajectory fallback
# ---------------------------------------------------------------------------
def test_m9_missing_trajectory_renders_fallback(tmp_path: Path) -> None:
    """No paths, missing path, or malformed JSON -> Mode line + 'run details unavailable'."""
    # Empty list.
    out = render_run_info_block([], "ttt", "0.14.0")
    assert "- **Mode:** ttt" in out
    assert "*run details unavailable*" in out

    # Path that doesn't exist.
    out2 = render_run_info_block([tmp_path / "nope.json"], "ttt", "0.14.0")
    assert "*run details unavailable*" in out2

    # Malformed JSON.
    bad = tmp_path / "bad.json"
    bad.write_text("{not json", encoding="utf-8")
    out3 = render_run_info_block([bad], "ttt", "0.14.0")
    assert "*run details unavailable*" in out3
    # Per-phase table must NOT render in fallback mode.
    assert "Per-phase breakdown" not in out3


# ---------------------------------------------------------------------------
# M10 — number formatting
# ---------------------------------------------------------------------------
def test_m10_number_formatting_rules(tmp_path: Path) -> None:
    """Thousand separators on >=1,000; sub-cent cost renders <$0.01; cache-hit
    omitted when input == 0."""
    # Sub-cent cost.
    p = _write_trajectory(
        tmp_path,
        name="subcent.json",
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="gpt-5.5",
                prompt=500,
                completion=10,
                cached=0,
                cost_usd=0.001,
            ),
        ],
    )
    out = render_run_info_block([p], "ttt", "0.14.0")
    assert "- **Cost:** <$0.01" in out
    # 500 in -> no thousand separator
    assert "500 in" in out
    # Input nonzero but cached=0 -> omit hit ratio.
    assert "0% hit" not in out
    assert "cached" not in out.split("**Tokens:**", 1)[1].split("\n", 1)[0]

    # Thousand separators in tokens line.
    p2 = _write_trajectory(
        tmp_path,
        name="big.json",
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="gpt-5.5",
                prompt=33_600,
                completion=6_900,
                cached=22_600,
                cost_usd=0.42,
            ),
        ],
    )
    out2 = render_run_info_block([p2], "ttt", "0.14.0")
    assert "33,600 in" in out2
    assert "22,600 cached" in out2
    assert "6,900 out" in out2

    # Zero-input edge: no hit ratio.
    p3 = _write_trajectory(
        tmp_path,
        name="zero_input.json",
        steps=[
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "go",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "ttt"},
            },
            _agent_step(
                step_id=2,
                phase="review",
                model="gpt-5.5",
                prompt=0,
                completion=10,
                cached=0,
                cost_usd=0.0,
            ),
        ],
    )
    out3 = render_run_info_block([p3], "ttt", "0.14.0")
    # Tokens line uses the no-cache form when input is 0.
    assert "0 in → 10 out" in out3


# ---------------------------------------------------------------------------
# Baseline single-phase render
# ---------------------------------------------------------------------------
def test_single_phase_run_renders_baseline() -> None:
    """The baseline single-phase Claude trajectory renders all sections cleanly."""
    out = render_run_info_block([_SINGLE_PHASE], "ttt", "0.14.0")
    # Rollup, table, footer all present.
    assert out.startswith("- **Mode:**")
    assert "<details><summary>Per-phase breakdown</summary>" in out
    assert out.rstrip().endswith("</sub>")
    # Single 'Review' phase row only.
    assert out.count("| Review |") == 1
    assert "| Fix |" not in out


# ---------------------------------------------------------------------------
# Purity / idempotence
# ---------------------------------------------------------------------------
def test_renderer_is_pure_idempotent() -> None:
    """Calling the renderer twice with identical inputs returns identical output.

    Pure function: no globals, no time.now(), no env. Two consecutive
    renders must be byte-equal. Catches accidental UUID generation,
    cache-busting timestamps, or random ordering of phase rows.
    """
    a = render_run_info_block([_MULTI_PHASE_CODEX], "deep review", "0.14.0")
    b = render_run_info_block([_MULTI_PHASE_CODEX], "deep review", "0.14.0")
    assert a == b


# ---------------------------------------------------------------------------
# S2 — deep-mode multi-trajectory aggregation
# ---------------------------------------------------------------------------
def test_aggregates_across_multiple_trajectory_files() -> None:
    """Sibling fork trajectories sum into the parent's per-phase rollup.

    multi_phase_codex.json: review (10K input, 5K cached, 1K out) +
                            fix    (8K input, 4K cached, 2K out).
    sibling_fix.json:       fix    (5K input, 2K cached, 0.5K out).

    Combined fix totals: 13K input, 6K cached, 2.5K output.
    Combined run totals: 23K input, 11K cached, 3.5K output.
    """
    out = render_run_info_block(
        [_MULTI_PHASE_CODEX, _SIBLING_FIX], "deep review", "0.14.0"
    )
    # Rollup totals.
    assert "23,000 in" in out
    assert "11,000 cached" in out
    assert "3,500 out" in out
    # Steps: 2 review-agent steps from multi_phase + ... wait, multi_phase
    # has 1 agent step in review and 1 in fix. sibling has 1 in fix.
    # So total agent steps = 3, tools = 1 + 2 + 1 = 4.
    assert "- **Steps / tool calls:** 3 / 4" in out
    # Fix row aggregates across both files: 13,000 input, 6,000 cached, 2,500 output.
    fix_row = next(line for line in out.splitlines() if line.startswith("| Fix |"))
    assert "13,000" in fix_row
    assert "6,000" in fix_row
    assert "2,500" in fix_row


# ---------------------------------------------------------------------------
# Defensive: a fork-only trajectory still uses Mode label & footer.
# ---------------------------------------------------------------------------
@pytest.mark.parametrize(
    "mode_label",
    ["comment", "feedback 123", "deep review", "trust-the-technology"],
)
def test_mode_label_round_trips_verbatim(mode_label: str) -> None:
    """Whatever string the caller hands in for Mode lands verbatim on the line."""
    out = render_run_info_block([_SINGLE_PHASE], mode_label, "0.14.0")
    assert f"- **Mode:** {mode_label}" in out
