"""Parser-drift contracts use committed real Codex output and an opt-in live probe.

The codex 0.139.0 golden at tests/fixtures/codex_jsonl/real/golden.jsonl is regenerated by
scripts/capture-codex-golden.sh. Structural assertions tolerate reworded text while checking tool
correlation, metrics, and valid trajectories.

DAYDREAM_CODEX_LIVE=1 enables the live_codex probe against the sample repository; it logs unknown
event types. Binary presence alone is insufficient because an unauthenticated CLI fails.

The separate sanitized codex 0.153.4 omission capture retains raw/sanitized digests. Its maintenance
script creates only an unpublished public candidate for exact-run corroboration and review.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from daydream.backends import (
    DiagnosticEvent,
    MetricsEvent,
    ResultEvent,
    TextEvent,
    ToolResultEvent,
    ToolStartEvent,
)
from daydream.backends.codex import CodexBackend
from tests.harness.codex_replay import FIXTURES_DIR, make_mock_process, make_mock_process_from_fixture

REAL_GOLDEN = "real/golden.jsonl"
REAL_GENERIC_TOOL_FAILURE = "real/generic-tool-failure.jsonl"
REAL_GENERIC_TOOL_FAILURE_META = "real/generic-tool-failure.meta.json"

_logger = logging.getLogger(__name__)

# Require explicit live opt-in; an installed but unauthenticated CLI would fail.
_CODEX_LIVE_OPT_IN = os.environ.get("DAYDREAM_CODEX_LIVE") == "1"
_CODEX_AVAILABLE = shutil.which("codex") is not None

def test_generic_tool_transport_capture_has_truthful_sanitized_provenance() -> None:
    """The genuine public capture is immutable apart from its declared path redaction."""
    capture_script = Path(__file__).parents[1] / "scripts" / "capture-codex-generic-tool-failure.sh"
    fixture_path = FIXTURES_DIR / REAL_GENERIC_TOOL_FAILURE
    metadata_path = FIXTURES_DIR / REAL_GENERIC_TOOL_FAILURE_META
    fixture_bytes = fixture_path.read_bytes()
    metadata = json.loads(metadata_path.read_text())
    records = [json.loads(line) for line in fixture_bytes.splitlines()]

    assert capture_script.is_file() and os.access(capture_script, os.X_OK)
    assert hashlib.sha256(fixture_bytes).hexdigest() == metadata["fixture_sha256_sanitized"]
    assert metadata["capture_sha256_raw"] == ("896389a5da72401e74ee50324bedd745c513cb7468fa5dcb0fbf682e4b125683")
    assert metadata["capture_sha256_raw"] != metadata["fixture_sha256_sanitized"]
    assert metadata["fixture_sanitized"] is True
    assert metadata["sanitizations"] == [{
            "field": "item.message", "occurrences": 1, "replacement": "/Users/[REDACTED_USER]/.codex/config.toml",
            "reason": "personal_home_path",
        }
    ]
    assert [record["type"]
        if record["type"] != "item.completed"
        else f"item.completed/{record['item']['type']}"
        for record in records
    ] == ["thread.started", "item.completed/error", "turn.started", "item.completed/error",
        "item.completed/agent_message", "item.completed/agent_message", "turn.completed",
    ]
    assert metadata["ordered_public_shape"] == [
        "thread.started", "item.completed/error", "turn.started", "item.completed/error",
        "item.completed/agent_message", "item.completed/agent_message", "turn.completed",
    ]
    assert metadata["cli_version"] == "0.153.4"
    assert metadata["captured_at_utc"] == "2026-09-06T02:31:50Z"
    assert metadata["capture_working_directory"] == "disposable_git_repo"
    assert metadata["public_flags"] == ["--json", "--sandbox", "read-only", "--enable", "code_mode"]
    assert metadata["exit_code"] == 0
    assert metadata["public_generic_function_items_exposed"] is False
    assert metadata["private_rollout_correlated"] is True
    assert metadata["private_custom_tool_calls"] == [
        {"name": "exec", "count": 1, "matching_outputs": 1, "error_class": "TypeError"}
    ]
    assert metadata["probe_prompt"] == (
        "This is a transport-contract probe. You MUST invoke the functions.exec tool exactly once "
        "with this exact JavaScript body: const r = await tools.wait({cell_id:\"definitely-missing-cell\","
        "yield_time_ms:250}); text(r); Do not call any other tool. Do not claim success unless you "
        "receive the tool output. Afterward report whether the nested wait call was visible to you "
        "and include its error category without inventing it."
    )

    public_items = [record["item"] for record in records if "item" in record]
    assert [item["type"] for item in public_items] == ["error", "error", "agent_message", "agent_message"]
    for item in public_items:
        assert not ({"name", "call_id", "arguments", "output"} & item.keys())

    fixture_text = fixture_bytes.decode()
    metadata_text = metadata_path.read_text()
    assert "/Users/ka" not in fixture_text
    assert "/Users/ka" not in metadata_text
    assert "definitely-missing-cell" not in fixture_text
    for forbidden_key in {
        "private_rollout_bytes", "private_session_path", "home_path", "environment_context", "credentials", "call_id",
        "arguments", "output_text",
    }:
        assert forbidden_key not in metadata

def test_capture_script_publishes_only_public_candidate_without_replacing_fixture(tmp_path: Path,) -> None:
    """A fake external CLI proves candidate capture is non-publishing and public-only."""
    capture_script = Path(__file__).parents[1] / "scripts" / "capture-codex-generic-tool-failure.sh"
    committed_fixture = FIXTURES_DIR / REAL_GENERIC_TOOL_FAILURE
    committed_metadata = FIXTURES_DIR / REAL_GENERIC_TOOL_FAILURE_META
    before_fixture = committed_fixture.read_bytes()
    before_metadata = committed_metadata.read_bytes()

    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    fake_codex = fake_bin / "codex"
    fake_codex.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'if [[ "${1:-}" == "--version" ]]; then\n'
        "  printf '%s\\n' 'codex-cli 9.9.9'\n"
        "  exit 0\n"
        "fi\n"
        # Read stdin before replying; early exit can race the producer and yield SIGPIPE under
        # pipefail.
        "IFS= read -r probe_prompt\n"
        'printf \'%s\\n\' "$probe_prompt" > "$FAKE_CODEX_PROBE_PATH"\n'
        'if [[ "${FAKE_CODEX_EXPOSE_PAIR:-}" == "1" ]]; then\n'
        "  printf '%s\\n' \\\n"
        "    '{\"type\":\"item.completed\",\"item\":{\"type\":\"error\"}}' \\\n"
        "    '{\"type\":\"item.completed\",\"item\":{"
        "\"type\":\"custom_tool_call\"}}' \\\n"
        "    '{\"type\":\"turn.completed\"}'\n"
        "  exit 0\n"
        "fi\n"
        "printf '%s\\n' \\\n"
        "  '{\"type\":\"thread.started\",\"thread_id\":\"candidate-thread\"}' \\\n"
        "  '{\"type\":\"item.completed\",\"item\":{\"id\":\"warning\","
        "\"type\":\"error\",\"message\":\"see /Users/fake-person/.codex/config.toml\"}}' \\\n"
        "  '{\"type\":\"turn.started\"}' \\\n"
        "  '{\"type\":\"turn.completed\",\"usage\":{\"input_tokens\":1,"
        "\"output_tokens\":1}}'\n"
    )
    fake_codex.chmod(0o755)
    candidate_root = tmp_path / "candidates"
    env = os.environ.copy()
    env["PATH"] = f"{fake_bin}{os.pathsep}{env['PATH']}"
    env["DAYDREAM_CODEX_CAPTURE_ROOT"] = str(candidate_root)
    probe_path = tmp_path / "received-probe.txt"
    env["FAKE_CODEX_PROBE_PATH"] = str(probe_path)
    env.pop("DAYDREAM_CODEX_PRIVATE_CORROBORATED", None)
    env.pop("DAYDREAM_CODEX_PRIVATE_ERROR_CLASS", None)

    captured = subprocess.run(
        [str(capture_script)], cwd=Path(__file__).parents[1], env=env, capture_output=True, text=True, check=False,
    )

    assert captured.returncode == 0, captured.stderr
    candidates = [path for path in candidate_root.iterdir() if not path.name.startswith(".")]
    assert len(candidates) == 1
    candidate_fixture = candidates[0] / "public.jsonl"
    candidate_metadata = candidates[0] / "public.meta.json"
    assert candidate_fixture.is_file() and candidate_metadata.is_file()
    metadata = json.loads(candidate_metadata.read_text())
    assert metadata["cli_version"] == "9.9.9"
    assert metadata["publication_status"] == "candidate_unpublished"
    assert probe_path.read_text() == metadata["probe_prompt"] + "\n"
    assert metadata["review_requirements"] == ["privately_correlate_this_exact_candidate_run_before_fixture_update"]
    assert not [key for key in metadata if key.startswith("private_")]
    assert hashlib.sha256(candidate_fixture.read_bytes()).hexdigest() == metadata["fixture_sha256_sanitized"]
    assert "/Users/fake-person" not in candidate_fixture.read_text()
    assert committed_fixture.read_bytes() == before_fixture
    assert committed_metadata.read_bytes() == before_metadata

    rejected_root = tmp_path / "rejected-candidates"
    env["DAYDREAM_CODEX_CAPTURE_ROOT"] = str(rejected_root)
    env["FAKE_CODEX_EXPOSE_PAIR"] = "1"
    rejected = subprocess.run(
        [str(capture_script)], cwd=Path(__file__).parents[1], env=env, capture_output=True, text=True, check=False,
    )
    assert rejected.returncode != 0
    assert "update the parser contract" in rejected.stderr
    assert not [path for path in rejected_root.iterdir() if not path.name.startswith(".")]
    assert committed_fixture.read_bytes() == before_fixture
    assert committed_metadata.read_bytes() == before_metadata

@pytest.mark.asyncio
async def test_generic_tool_transport_capture_maps_only_public_error_sentinel() -> None:
    backend = CodexBackend(model="gpt-5.5")
    mock_proc = make_mock_process_from_fixture(REAL_GENERIC_TOOL_FAILURE)
    with patch("daydream.backends._transport.asyncio.create_subprocess_exec", return_value=mock_proc):
        events = [event async for event in backend.execute(Path("/tmp"), "transport contract")]
    diagnostics = [event for event in events if isinstance(event, DiagnosticEvent)]
    assert [event.code for event in diagnostics] == ["codex_transport_coverage", "codex_transport_coverage"]
    assert diagnostics[0].metadata["occurrences"] == 1
    assert diagnostics[-1].metadata == {
        "coverage": "incomplete", "reason": "uncorrelated_public_error_item", "occurrences": 2,
        "contract": "codex-cli-0.153.4-json-code-mode",
    }
    assert not [event for event in events if isinstance(event, (ToolStartEvent, ToolResultEvent))]

@pytest.mark.asyncio
async def test_real_golden_has_no_parser_or_transport_diagnostic() -> None:
    backend = CodexBackend(model="gpt-5.5")
    mock_proc = make_mock_process_from_fixture(REAL_GOLDEN)
    with patch("daydream.backends._transport.asyncio.create_subprocess_exec", return_value=mock_proc):
        events = [event async for event in backend.execute(Path("/tmp"), "golden contract")]

    assert not [event for event in events if isinstance(event, DiagnosticEvent)]

@pytest.mark.asyncio
async def test_real_golden_parses_to_expected_events() -> None:
    """Parse the real golden structurally: text, paired tools without orphans, per-turn metrics, and a
    terminal result. Reworded model output must not break the contract.
    """
    assert (FIXTURES_DIR / REAL_GOLDEN).exists(), (f"real golden missing at {FIXTURES_DIR / REAL_GOLDEN}")

    backend = CodexBackend(model="gpt-5.5")
    mock_proc = make_mock_process_from_fixture(REAL_GOLDEN)

    with patch("daydream.backends._transport.asyncio.create_subprocess_exec", return_value=mock_proc):
        events: list[Any] = []
        async for event in backend.execute(Path("/tmp"), "Read README.md then hello.py"):
            events.append(event)

    text_events = [e for e in events if isinstance(e, TextEvent)]
    assert text_events, "real golden produced no TextEvent (agent_message lost)"

    tool_starts = [e for e in events if isinstance(e, ToolStartEvent)]
    tool_results = [e for e in events if isinstance(e, ToolResultEvent)]
    assert len(tool_starts) == 2, f"expected 2 tool starts, got {len(tool_starts)}"
    assert len(tool_results) == 2, f"expected 2 tool results, got {len(tool_results)}"

    start_ids = {e.id for e in tool_starts}
    result_ids = {e.id for e in tool_results}
    assert result_ids == start_ids, (f"orphaned tool result on real data: starts={start_ids} results={result_ids}")

    metrics_events = [e for e in events if isinstance(e, MetricsEvent)]
    assert metrics_events, "real golden produced no MetricsEvent (usage lost)"
    mev = metrics_events[0]
    assert mev.prompt_tokens is not None and mev.prompt_tokens > 0, (
        f"real usage input_tokens not surfaced: {mev.prompt_tokens}"
    )
    assert mev.completion_tokens is not None and mev.completion_tokens > 0, (
        f"real usage output_tokens not surfaced: {mev.completion_tokens}"
    )
    assert mev.cached_tokens is not None and mev.cached_tokens > 0, (
        f"real cached_input_tokens not surfaced: {mev.cached_tokens}"
    )
    # Reasoning tokens are a subset of completion tokens, never additive.
    assert mev.reasoning_tokens is not None and mev.reasoning_tokens > 0, (
        f"real reasoning_output_tokens not surfaced: {mev.reasoning_tokens}"
    )
    # The fixture model has a known price, so its nonzero usage must produce positive cost.
    assert mev.cost_usd is not None and mev.cost_usd > 0, (
        f"real golden cost not synthesized for gpt-5.5: {mev.cost_usd}"
    )

    result_events = [e for e in events if isinstance(e, ResultEvent)]
    assert result_events, "real golden produced no ResultEvent"

@pytest.mark.live_codex
@pytest.mark.asyncio
@pytest.mark.skipif(not (_CODEX_AVAILABLE and _CODEX_LIVE_OPT_IN),
    reason="live codex smoke test; set DAYDREAM_CODEX_LIVE=1 (and ensure `codex` is on $PATH and logged in) to run",
)
async def test_codex_live_smoke() -> None:
    """Opt-in live probe of process arguments, parsing, and trajectory recording. Unknown JSONL event
    types are logged at WARNING for triage.
    """
    sample_repo = Path(__file__).parent / "fixtures" / "real_cli_sample_repo"
    prompt = "Read README.md and summarize it in one sentence."

    proc = await asyncio.create_subprocess_exec(
        "codex", "exec", "--experimental-json", "--sandbox", "read-only", "--cd", str(sample_repo),
        stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
    )
    if proc.stdout is None or proc.stdin is None:
        pytest.skip("could not open codex stdio")
    proc.stdin.write(prompt.encode())
    proc.stdin.close()

    # Log malformed JSON and unknown event types as parser-drift evidence.
    known_types = {"thread.started", "turn.started", "turn.completed", "turn.failed", "item.started", "item.updated",
        "item.completed", "error",
    }
    # Failure events must fail the live probe; quota and rate limits are environmental skip
    # conditions.
    failure_types = {"turn.failed", "error"}
    quota_markers = ("usage limit", "rate limit", "quota", "credit", "upgrade to pro", "try again at")
    lines: list[str] = []
    failures: list[str] = []
    failure_messages: list[str] = []
    assert proc.stdout is not None
    while True:
        raw = await proc.stdout.readline()
        if not raw:
            break
        text = raw.decode().strip()
        if not text:
            continue
        try:
            evt = json.loads(text)
        except json.JSONDecodeError:
            _logger.warning("codex live smoke: non-JSON line: %r", text[:120])
            continue
        etype = evt.get("type", "")
        if etype not in known_types:
            _logger.warning("codex live smoke: unrecognized event type %r", etype)
        if etype in failure_types:
            failures.append(etype)
            msg = evt.get("message") or evt.get("error", {})
            if isinstance(msg, dict):
                msg = msg.get("message", "")
            if isinstance(msg, str) and msg:
                failure_messages.append(msg)
        lines.append(text)
    rc = await proc.wait()

    assert lines, "codex live smoke produced no JSONL output"

    joined = " ".join(failure_messages).lower()
    if rc != 0 or failures:
        if any(marker in joined for marker in quota_markers):
            pytest.skip(f"codex live smoke hit an environmental limit (rc={rc}): {failure_messages[:1]}")
        assert rc == 0, f"codex live smoke exited non-zero: rc={rc}"
        assert not failures, f"codex live smoke reported failure events: {failures}"

    backend = CodexBackend(model="live-smoke-model")

    with patch("daydream.backends._transport.asyncio.create_subprocess_exec", return_value=make_mock_process(lines)):
        events: list[Any] = []
        async for event in backend.execute(sample_repo, prompt):
            events.append(event)

    assert events, "codex live smoke parsed to an empty AgentEvent stream"
