"""Tests for ``daydream summarize <path>``.

Covers single-file, run-directory, missing-path, and unparseable inputs,
plus parity with calling ``render_run_info_block`` directly.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from daydream.pr_comment_renderer import render_run_info_block
from daydream.summarize import summarize

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "trajectories"
_DEEP_PARENT = _FIXTURE_DIR / "deep_mode_parent.json"
_DEEP_FORK_A = _FIXTURE_DIR / "deep_mode_fork_a.json"
_DEEP_FORK_B = _FIXTURE_DIR / "deep_mode_fork_b.json"
_SINGLE_PHASE = _FIXTURE_DIR / "single_phase_claude.json"


def test_single_trajectory_file_produces_renderer_output(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """A single .json trajectory file is fed straight through the renderer."""
    rc = summarize(_SINGLE_PHASE)
    assert rc == 0
    captured = capsys.readouterr()
    assert "- **Model:**" in captured.out
    assert "<details><summary>Per-phase breakdown</summary>" in captured.out
    assert "<sub>Generated by daydream v" in captured.out
    # Mode line is gone from summarize output too.
    assert "**Mode:**" not in captured.out


def test_run_directory_with_parent_and_forks(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A run dir with trajectory.json + 2 fork siblings aggregates all three."""
    run_dir = tmp_path / "runs" / "abcd1234-fixture"
    run_dir.mkdir(parents=True)
    shutil.copy(_DEEP_PARENT, run_dir / "trajectory.json")
    siblings = run_dir / "trajectories"
    siblings.mkdir()
    shutil.copy(_DEEP_FORK_A, siblings / "fix-0.json")
    shutil.copy(_DEEP_FORK_B, siblings / "fix-1.json")

    rc = summarize(run_dir)
    assert rc == 0
    out = capsys.readouterr().out
    # Aggregate cost / token totals from the deep-mode fixtures.
    assert "- **Cost:** $0.19" in out
    assert "14,000 in" in out
    # Fix row aggregates across both forks.
    fix_row = next(line for line in out.splitlines() if line.startswith("| Fix |"))
    assert "5,000" in fix_row


def test_nonexistent_path_returns_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Missing path: clear stderr message + non-zero exit."""
    rc = summarize(tmp_path / "no-such-thing.json")
    assert rc != 0
    err = capsys.readouterr().err
    assert "does not exist" in err


def test_directory_without_trajectories_returns_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """An empty directory with no trajectory files: clear stderr + non-zero exit."""
    empty = tmp_path / "empty-run"
    empty.mkdir()
    rc = summarize(empty)
    assert rc != 0
    err = capsys.readouterr().err
    assert "no trajectory" in err.lower()


def test_directory_with_only_unparseable_trajectories_falls_back(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """All trajectories failed to parse → renderer fallback → non-zero exit."""
    run_dir = tmp_path / "broken-run"
    run_dir.mkdir()
    (run_dir / "trajectory.json").write_text("{not json", encoding="utf-8")

    rc = summarize(run_dir)
    out = capsys.readouterr().out
    assert "*run details unavailable*" in out
    # The renderer fallback signals "no real summary produced" via non-zero.
    assert rc != 0


def test_summarize_matches_render_run_info_block_directly(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Summarize on a run dir matches calling render_run_info_block with the same paths."""
    run_dir = tmp_path / "runs" / "abcd1234-parity"
    run_dir.mkdir(parents=True)
    shutil.copy(_DEEP_PARENT, run_dir / "trajectory.json")
    siblings = run_dir / "trajectories"
    siblings.mkdir()
    shutil.copy(_DEEP_FORK_A, siblings / "fix-0.json")
    shutil.copy(_DEEP_FORK_B, siblings / "fix-1.json")

    rc = summarize(run_dir)
    assert rc == 0
    summarize_out = capsys.readouterr().out.rstrip("\n")

    expected = render_run_info_block(
        [
            run_dir / "trajectory.json",
            siblings / "fix-0.json",
            siblings / "fix-1.json",
        ]
    )
    assert summarize_out == expected


def test_non_json_file_rejected(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A file with the wrong suffix isn't fed to the renderer."""
    bad = tmp_path / "trajectory.txt"
    bad.write_text(json.dumps({"schema_version": "ATIF-v1.6"}), encoding="utf-8")
    rc = summarize(bad)
    assert rc != 0
    err = capsys.readouterr().err
    assert ".json" in err
