from daydream.generated_files import is_generated_file, related_manifest_paths


def test_generated_sql_migration() -> None:
    assert is_generated_file("migrations/0001_init.sql")
    assert is_generated_file("backend/migrations/20240101_add_x.sql")
    assert is_generated_file("alembic/versions/abc123_add_col.py")


def test_non_generated_source_allowed() -> None:
    assert not is_generated_file("src/app.py")
    assert not is_generated_file("daydream/phases.py")


def test_codegen_and_lockfiles() -> None:
    assert is_generated_file("internal/model_generated.go")
    assert is_generated_file("Cargo.lock")
    assert is_generated_file("package-lock.json")
    assert is_generated_file("uv.lock")
    assert not is_generated_file("Cargo.toml")
    assert not is_generated_file("requirements.txt")


def test_generated_marker_headers() -> None:
    assert is_generated_file("src/client.py", "# @generated\n")
    assert is_generated_file("src/client.go", "// Code generated by protoc. DO NOT EDIT.\n")
    assert is_generated_file("src/client.txt", "Code generated by tool. DO NOT EDIT.\n")
    assert not is_generated_file("src/client.py", "# generated at runtime\n")
    assert not is_generated_file("src/client.py", "def client():\n    pass\n# @generated\n")


def test_lockfile_manifest_pairs() -> None:
    assert related_manifest_paths("Cargo.lock") == ("Cargo.toml",)
    assert related_manifest_paths("frontend/package-lock.json") == ("frontend/package.json",)
    assert related_manifest_paths("src/app.py") == ()
