"""Tests for ``daydream summarize <path>``.

Covers single-file, run-directory, missing-path, and unparseable inputs,
plus parity with calling ``render_run_info_block`` directly.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from daydream.pr_comment_renderer import render_run_info_block
from daydream.summarize import summarize

_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "trajectories"
_DEEP_PARENT = _FIXTURE_DIR / "deep_mode_parent.json"
_DEEP_FORK_A = _FIXTURE_DIR / "deep_mode_fork_a.json"
_DEEP_FORK_B = _FIXTURE_DIR / "deep_mode_fork_b.json"
_SINGLE_PHASE = _FIXTURE_DIR / "single_phase_claude.json"


def test_single_trajectory_file_produces_renderer_output(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """A single .json trajectory file is fed straight through the renderer."""
    rc = summarize(_SINGLE_PHASE)
    assert rc == 0
    captured = capsys.readouterr()
    assert "- **Model:**" in captured.out
    assert "<details><summary>Per-phase breakdown</summary>" in captured.out
    assert "<sub>Generated by daydream v" in captured.out
    # Mode line is gone from summarize output too.
    assert "**Mode:**" not in captured.out


def test_run_directory_with_parent_and_forks(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A run dir with trajectory.json + 2 fork siblings aggregates all three."""
    run_dir = tmp_path / "runs" / "abcd1234-fixture"
    run_dir.mkdir(parents=True)
    shutil.copy(_DEEP_PARENT, run_dir / "trajectory.json")
    siblings = run_dir / "trajectories"
    siblings.mkdir()
    shutil.copy(_DEEP_FORK_A, siblings / "fix-0.json")
    shutil.copy(_DEEP_FORK_B, siblings / "fix-1.json")

    rc = summarize(run_dir)
    assert rc == 0
    out = capsys.readouterr().out
    # Aggregate cost / token totals from the deep-mode fixtures.
    assert "- **Cost:** $0.19" in out
    assert "14,000 in" in out
    # Fix row aggregates across both forks.
    fix_row = next(line for line in out.splitlines() if line.startswith("| Fix |"))
    assert "5,000" in fix_row


def test_nonexistent_path_returns_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Missing path: clear stderr message + non-zero exit."""
    rc = summarize(tmp_path / "no-such-thing.json")
    assert rc != 0
    err = capsys.readouterr().err
    assert "does not exist" in err


def test_directory_without_trajectories_returns_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """An empty directory with no trajectory files: clear stderr + non-zero exit."""
    empty = tmp_path / "empty-run"
    empty.mkdir()
    rc = summarize(empty)
    assert rc != 0
    err = capsys.readouterr().err
    assert "no trajectory" in err.lower()


def test_directory_with_only_unparseable_trajectories_falls_back(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """All trajectories failed to parse → renderer fallback → non-zero exit."""
    run_dir = tmp_path / "broken-run"
    run_dir.mkdir()
    (run_dir / "trajectory.json").write_text("{not json", encoding="utf-8")

    rc = summarize(run_dir)
    out = capsys.readouterr().out
    assert "*run details unavailable*" in out
    # The renderer fallback signals "no real summary produced" via non-zero.
    assert rc != 0


def test_summarize_matches_render_run_info_block_directly(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Summarize on a run dir matches calling render_run_info_block with the same paths."""
    run_dir = tmp_path / "runs" / "abcd1234-parity"
    run_dir.mkdir(parents=True)
    shutil.copy(_DEEP_PARENT, run_dir / "trajectory.json")
    siblings = run_dir / "trajectories"
    siblings.mkdir()
    shutil.copy(_DEEP_FORK_A, siblings / "fix-0.json")
    shutil.copy(_DEEP_FORK_B, siblings / "fix-1.json")

    rc = summarize(run_dir)
    assert rc == 0
    summarize_out = capsys.readouterr().out.rstrip("\n")

    expected = render_run_info_block(
        [
            run_dir / "trajectory.json",
            siblings / "fix-0.json",
            siblings / "fix-1.json",
        ]
    )
    assert summarize_out == expected


def test_non_json_file_rejected(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A file with the wrong suffix isn't fed to the renderer."""
    bad = tmp_path / "trajectory.txt"
    bad.write_text(json.dumps({"schema_version": "ATIF-v1.6"}), encoding="utf-8")
    rc = summarize(bad)
    assert rc != 0
    err = capsys.readouterr().err
    assert ".json" in err


# --- User-overridable pricing through the summarize entrypoint ----------------

# Model name deliberately absent from built-in MODEL_PRICES (gpt-5.5,
# gpt-5.5-pro, gpt-5-codex, gpt-5.3-codex), so the only way the cost cell can
# render a dollar value is via a user-supplied price override.
_CUSTOM_MODEL = "my-custom-model"

# Chosen so the synthesized cost lands on a clean string the renderer emits:
#   uncached_input = 100_000, cached = 0, output = 50_000
#   input price 10.0/1M, output price 20.0/1M  ->
#   100_000 * 10 / 1e6 + 50_000 * 20 / 1e6 = 1.00 + 1.00 = $2.00
_PROMPT_TOKENS = 100_000
_CACHED_TOKENS = 0
_COMPLETION_TOKENS = 50_000
_INPUT_PRICE = 10.0
_OUTPUT_PRICE = 20.0
_EXPECTED_COST_CELL = "$2.00"


def _write_custom_model_trajectory(tmp_path: Path) -> Path:
    """Write a minimal ATIF v1.6 trajectory with one priced-but-unknown step.

    The single agent step carries token metrics, NO ``cost_usd``, and a
    ``model_name`` not present in built-in ``MODEL_PRICES`` — so the cost cell
    can only resolve to a dollar value when a user price override is loaded.
    """
    traj = {
        "schema_version": "ATIF-v1.6",
        "session_id": "fixture-custom-model-summarize",
        "agent": {
            "name": "daydream",
            "version": "0.14.0",
            "model_name": _CUSTOM_MODEL,
        },
        "steps": [
            {
                "step_id": 1,
                "timestamp": "2026-05-02T00:00:00.000000Z",
                "source": "user",
                "message": "review",
                "extra": {"daydream_phase": "review", "daydream_run_flow": "normal"},
            },
            {
                "step_id": 2,
                "timestamp": "2026-05-02T00:00:01.000000Z",
                "source": "agent",
                "model_name": _CUSTOM_MODEL,
                "message": "Reviewed.",
                "tool_calls": [
                    {"tool_call_id": "r1", "function_name": "Read", "arguments": {}}
                ],
                "observation": {"results": [{"source_call_id": "r1", "content": "ok"}]},
                "metrics": {
                    "prompt_tokens": _PROMPT_TOKENS,
                    "completion_tokens": _COMPLETION_TOKENS,
                    "cached_tokens": _CACHED_TOKENS,
                    "cost_usd": None,
                },
                "extra": {"daydream_phase": "review", "daydream_run_flow": "normal"},
            },
        ],
        "final_metrics": {
            "total_prompt_tokens": _PROMPT_TOKENS,
            "total_completion_tokens": _COMPLETION_TOKENS,
            "total_cached_tokens": _CACHED_TOKENS,
            "total_steps": 2,
        },
    }
    traj_path = tmp_path / "trajectory.json"
    traj_path.write_text(json.dumps(traj), encoding="utf-8")
    return traj_path


def _write_prices_toml(tmp_path: Path) -> Path:
    """Write a prices.toml covering the custom model with clean values."""
    prices_path = tmp_path / "prices.toml"
    prices_path.write_text(
        f'[prices."{_CUSTOM_MODEL}"]\n'
        f"input = {_INPUT_PRICE}\n"
        f"output = {_OUTPUT_PRICE}\n",
        encoding="utf-8",
    )
    return prices_path


def test_summarize_uses_user_price_override_for_unknown_model(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """POSITIVE: a prices.toml override makes the cost cell render a real $ value.

    Drives the production ``summarize`` entrypoint with DAYDREAM_PRICES_FILE
    pointing at a TOML that prices a model absent from built-in MODEL_PRICES.
    Asserts on the rendered markdown only: the synthesized cost cell and the
    absence of the unknown-model footnote.
    """
    traj = _write_custom_model_trajectory(tmp_path)
    prices_file = _write_prices_toml(tmp_path)
    monkeypatch.setenv("DAYDREAM_PRICES_FILE", str(prices_file))

    rc = summarize(traj)
    assert rc == 0
    out = capsys.readouterr().out

    # Rollup cost line and the per-phase Fix/Review row both carry the synthesized $2.00.
    assert f"- **Cost:** {_EXPECTED_COST_CELL}" in out
    review_row = next(line for line in out.splitlines() if line.startswith("| Review |"))
    assert _EXPECTED_COST_CELL in review_row
    assert "| — |" not in review_row
    # No footnote — the model WAS priced via the override.
    assert "not in the price table" not in out


def test_summarize_unknown_model_no_prices_renders_dash_and_footnote(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """NEGATIVE: with no price override the cost cell is — and the footnote appears.

    Same trajectory, but DAYDREAM_PRICES_FILE is unset, so the custom model is
    unpriced: the cost cell degrades to ``—`` and the renderer emits the
    'not in the price table' footnote naming the model.
    """
    traj = _write_custom_model_trajectory(tmp_path)
    # Point at a nonexistent file: neutralizes both a stray env var AND the
    # ~/.daydream/prices.toml home-dir fallback, so no price table loads.
    monkeypatch.setenv("DAYDREAM_PRICES_FILE", str(tmp_path / "no-such-prices.toml"))

    rc = summarize(traj)
    assert rc == 0
    out = capsys.readouterr().out

    assert "- **Cost:** —" in out
    review_row = next(line for line in out.splitlines() if line.startswith("| Review |"))
    assert "| — |" in review_row
    assert _EXPECTED_COST_CELL not in review_row
    assert f"<sub>Cost unavailable: model `{_CUSTOM_MODEL}` is not in the price table.</sub>" in out
