# One PR snapshot, baked. Tagged `<manifest image>:<head_sha[:12]>`, which is
# exactly what DaydreamReviewTaskset.load() stamps onto the task
# (daydream_review_v1/taskset.py:383) — one image is one reviewable commit.
#
# The final layer re-runs the repository's own test suite at that commit. A red
# suite MUST fail the build: suite_non_regression rewards a rollout for turning
# a red suite green, so a baseline that was already red turns that reward into
# noise and the run is unusable as a gradient. Better to lose the image than to
# ship a task whose reward means nothing.

# BASE_IMAGE is supplied as a build-arg by images/build_images.py and must be an
# immutable identity (daydream-rl/base:<tag> or daydream-rl/base@sha256:<64 hex>).
# There is deliberately no default: a snapshot build that omits it must fail, not
# silently fall back to a mutable alias that can move under the image.
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG HEAD_SHA
ARG BASE_SHA
ARG TEST_COMMAND

# The build context already holds a bare mirror, written by build_images.py.
# Only the git/mirror layer is mirror-only: it clones from the in-container
# mirror and never touches the network. The per-repo setup_cmds layer below,
# however, runs `uv sync --locked` (manifest.toml) and fetches the locked
# dependency set from the package index at build time — so for images with
# non-empty setup_cmds, the image does NOT rebuild from a stale corpus with
# no index access.
COPY mirror.git /srv/mirror.git

# `origin` therefore points at the in-container mirror. That is deliberate:
# daydream's deep flow ends by committing and pushing its fix, and against this
# origin that push stays inside the container and needs no credentials — no
# token is ever mounted into a rollout, and no rollout can reach the real repo.
#
# cat-file -e proves the base commit is present before the suite ever runs. The
# harness passes `--base ${BASE_SHA}` (harness.py:105-117), so a base missing
# from the mirror would surface as an empty diff at rollout time instead of as a
# build failure here.
RUN git clone /srv/mirror.git /work/repo \
 && git -C /work/repo checkout --detach ${HEAD_SHA} \
 && git -C /work/repo cat-file -e "${BASE_SHA}^{commit}"

# Per-repo dependency install, generated by build_images.py from the manifest
# entry's `setup_cmds`. An empty list yields a no-op script rather than a
# conditional COPY, so every repo image has the same layer shape.
COPY setup.sh /tmp/setup.sh
RUN cd /work/repo && sh /tmp/setup.sh

# The green-baseline gate. Unquoted on purpose: TEST_COMMAND is a shell command
# line from the manifest, not a single argv element. If this fails, the build
# fails and no image is produced — that is the enforcement, not a warning.
RUN cd /work/repo && ${TEST_COMMAND}

# The image clones as root (no USER directive), so hand the whole cloned tree
# to the agent identity at build time — the deep flow's first write
# (.daydream/, patch, git add/commit/push) runs as the agent uid. This sits
# after the root-run setup.sh/TEST_COMMAND layers so their outputs (e.g. .venv
# from uv sync) are agent-owned too. Defense-in-depth: the harness re-chowns
# the checkout and mirror at launch (harness.py:155-157), and this layer is
# idempotent against that handoff.
RUN chown -R agent:agent /work/repo

WORKDIR /work/repo
