"""Repository Git/GitHub boundary.

Public operations are grouped by responsibility; all process execution and
retry/redaction policy lives in ``process``. ``queries`` reads Git, ``state``
captures and restores exact paths, ``mutations`` changes refs and worktrees,
``snapshot`` prepares isolated storage, and ``github`` owns API payloads.
"""

from daydream.git_ops.auth import (
    INHERIT_GITHUB_AUTH as INHERIT_GITHUB_AUTH,
    GitHubAuth as GitHubAuth,
    InheritGitHubAuth as InheritGitHubAuth,
    RefreshingGitHubAuth as RefreshingGitHubAuth,
    StaticGitHubAuth as StaticGitHubAuth,
)
from daydream.git_ops.github import (
    GH_PR_LIST_FIELDS as GH_PR_LIST_FIELDS,
    GH_PR_VIEW_FIELDS as GH_PR_VIEW_FIELDS,
    gh_active_branch_rules as gh_active_branch_rules,
    gh_api as gh_api,
    gh_api_bounded_pages as gh_api_bounded_pages,
    gh_classic_required_checks as gh_classic_required_checks,
    gh_file_at_ref as gh_file_at_ref,
    gh_issue_create as gh_issue_create,
    gh_issue_list as gh_issue_list,
    gh_issue_list_strict as gh_issue_list_strict,
    gh_pr_ci_snapshot as gh_pr_ci_snapshot,
    gh_pr_create as gh_pr_create,
    gh_pr_diff as gh_pr_diff,
    gh_pr_list_for_branch as gh_pr_list_for_branch,
    gh_pr_view as gh_pr_view,
    gh_repo_view as gh_repo_view,
    gh_repo_view_required as gh_repo_view_required,
    gh_secret_list as gh_secret_list,
    gh_secret_set as gh_secret_set,
    gh_variable_list as gh_variable_list,
    gh_variable_set as gh_variable_set,
)
from daydream.git_ops.models import (
    BranchNotFoundError as BranchNotFoundError,
    DeadlineExpired as DeadlineExpired,
    GitError as GitError,
    GitHubPageLimits as GitHubPageLimits,
    GitHubRequestBudget as GitHubRequestBudget,
    GitPathState as GitPathState,
    GitTimeoutError as GitTimeoutError,
    IndependentSnapshot as IndependentSnapshot,
    IndexSnapshot as IndexSnapshot,
    NotAWorktreeError as NotAWorktreeError,
    PathAbsentError as PathAbsentError,
    RateLimitError as RateLimitError,
    RawIndexSnapshot as RawIndexSnapshot,
    SnapshotPreparationError as SnapshotPreparationError,
    WorktreeRollbackSnapshot as WorktreeRollbackSnapshot,
    WrongBranchError as WrongBranchError,
)
from daydream.git_ops.mutations import (
    apply_staged_patch as apply_staged_patch,
    apply_worktree_patch as apply_worktree_patch,
    checkout_branch as checkout_branch,
    checkout_detach as checkout_detach,
    clone as clone,
    clone_with_token as clone_with_token,
    commit_paths as commit_paths,
    commit_staged as commit_staged,
    create_branch as create_branch,
    fetch as fetch,
    push_branch as push_branch,
    registered_worktree_containing as registered_worktree_containing,
    remove_remote as remove_remote,
    restore_paths_from_ref as restore_paths_from_ref,
    restore_worktree_paths_from_ref as restore_worktree_paths_from_ref,
    stage_paths as stage_paths,
    update_refs as update_refs,
    worktree_add as worktree_add,
    worktree_lock_mtime as worktree_lock_mtime,
    worktree_move as worktree_move,
    worktree_patch_applies as worktree_patch_applies,
    worktree_remove as worktree_remove,
    worktree_remove_unlocked as worktree_remove_unlocked,
    worktree_unlock as worktree_unlock,
)
from daydream.git_ops.process import GH_CREDENTIAL_HELPER as GH_CREDENTIAL_HELPER
from daydream.git_ops.queries import (
    assert_is_worktree as assert_is_worktree,
    branch_exists as branch_exists,
    changed_files as changed_files,
    changed_files_against as changed_files_against,
    changed_paths_z as changed_paths_z,
    check_ignore as check_ignore,
    commit_exists as commit_exists,
    current_branch as current_branch,
    daydream_commits as daydream_commits,
    default_branch as default_branch,
    diff as diff,
    diff_name_only as diff_name_only,
    diff_name_only_strict as diff_name_only_strict,
    diff_paths as diff_paths,
    diff_worktree_against as diff_worktree_against,
    git_common_dir as git_common_dir,
    git_dir as git_dir,
    git_dirs as git_dirs,
    git_ls_remote as git_ls_remote,
    grep_fixed_matches as grep_fixed_matches,
    has_executable_pre_push_hook as has_executable_pre_push_hook,
    head_sha as head_sha,
    init_repository as init_repository,
    is_ancestor as is_ancestor,
    is_inside_worktree as is_inside_worktree,
    is_unborn_head as is_unborn_head,
    list_local_branches as list_local_branches,
    list_remotes as list_remotes,
    list_untracked as list_untracked,
    log as log,
    log_shas as log_shas,
    log_shas_since as log_shas_since,
    ls_files as ls_files,
    ls_tree_files as ls_tree_files,
    merge_base as merge_base,
    object_alternates as object_alternates,
    ref_exists as ref_exists,
    remote_contains_commit as remote_contains_commit,
    remote_url as remote_url,
    remote_urls as remote_urls,
    resolve_diff_merge_base as resolve_diff_merge_base,
    resolve_pr_merge_base as resolve_pr_merge_base,
    show as show,
    split_owner_repo as split_owner_repo,
    staged_patch as staged_patch,
    stash_create as stash_create,
    status_porcelain as status_porcelain,
    symbolic_head as symbolic_head,
    tracked_artifact_collisions as tracked_artifact_collisions,
    tracked_path_collisions as tracked_path_collisions,
    upstream_ahead_count as upstream_ahead_count,
    validate_branch_name as validate_branch_name,
)
from daydream.git_ops.snapshot import prepare_independent_snapshot as prepare_independent_snapshot
from daydream.git_ops.state import (
    build_recommended_patch_strict as build_recommended_patch_strict,
    copy_worktree_paths as copy_worktree_paths,
    restore_group_from_snapshot as restore_group_from_snapshot,
    restore_group_worktree_from_snapshot as restore_group_worktree_from_snapshot,
    restore_index as restore_index,
    restore_raw_index as restore_raw_index,
    snapshot_commit_paths as snapshot_commit_paths,
    snapshot_ignored_owner_paths as snapshot_ignored_owner_paths,
    snapshot_index as snapshot_index,
    snapshot_index_paths as snapshot_index_paths,
    snapshot_raw_index as snapshot_raw_index,
    snapshot_untracked_paths as snapshot_untracked_paths,
    snapshot_worktree_delta as snapshot_worktree_delta,
    snapshot_worktree_gitlinks as snapshot_worktree_gitlinks,
    snapshot_worktree_paths as snapshot_worktree_paths,
    tree_key as tree_key,
)
