"""``daydream summarize <path>`` — print run-info markdown to stdout.

Reads either a single ATIF v1.6 trajectory JSON file or a daydream run
directory (``runs/<session_id>/`` shape with a ``trajectory.json`` plus
optional ``trajectories/<descriptor>.json`` siblings) and prints the same
rollup + per-phase breakdown table the PR-comment renderer emits, followed
by the ``<sub>Generated by daydream vX.Y.Z</sub>`` footer.

No GitHub posting, no filtering, no diff. Pure read + render + print.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from daydream.eval.analyzer import collect_trajectory_paths
from daydream.pr_comment_renderer import FALLBACK_NOTE, render_run_info_block
from daydream.ui import NEON_THEME, print_error


def summarize(path: Path) -> int:
    """Print the run-info markdown for *path* to stdout.

    Returns:
        0 on success, non-zero when the path could not be resolved or no
        parseable trajectory could be produced.
    """
    # Errors go to stderr so stdout stays clean for the markdown summary.
    err_console = Console(stderr=True, theme=NEON_THEME)

    if not path.exists():
        print_error(err_console, "Invalid Path", f"path does not exist: {path}")
        return 1

    if path.is_file():
        if path.suffix != ".json":
            print_error(
                err_console,
                "Invalid Path",
                f"file must be a .json trajectory: {path}",
            )
            return 1
        paths = [path]
    elif path.is_dir():
        paths = collect_trajectory_paths(path)
        if not paths:
            print_error(
                err_console,
                "Invalid Path",
                f"no trajectory.json or trajectories/ found under {path}",
            )
            return 1
    else:
        print_error(
            err_console,
            "Invalid Path",
            f"path is not a file or directory: {path}",
        )
        return 1

    output = render_run_info_block(paths)
    print(output)

    # Renderer fell back because every input failed to parse — surface a
    # non-zero exit so callers know they didn't get a real summary.
    if FALLBACK_NOTE in output:
        return 2
    return 0


__all__ = ["summarize"]
