"""``daydream summarize <path>`` — print run-info markdown to stdout.

Reads either a single ATIF v1.6 trajectory JSON file or a daydream run
directory (``runs/<session_id>/`` shape with a ``trajectory.json`` plus
optional ``trajectories/<descriptor>.json`` siblings) and prints the same
rollup + per-phase breakdown table the PR-comment renderer emits, followed
by the ``<sub>Generated by daydream vX.Y.Z</sub>`` footer.

No GitHub posting, no filtering, no diff. Pure read + render + print.
"""

from __future__ import annotations

import sys
from pathlib import Path

from daydream.pr_comment_renderer import render_run_info_block

_FALLBACK_NOTE = "*run details unavailable*"


def summarize(path: Path) -> int:
    """Print the run-info markdown for *path* to stdout.

    Args:
        path: Either a trajectory JSON file or a run directory.

    Returns:
        0 on success, non-zero when the path could not be resolved or no
        parseable trajectory could be produced.
    """
    if not path.exists():
        print(f"daydream summarize: path does not exist: {path}", file=sys.stderr)
        return 1

    if path.is_file():
        if path.suffix != ".json":
            print(
                f"daydream summarize: file must be a .json trajectory: {path}",
                file=sys.stderr,
            )
            return 1
        paths = [path]
    elif path.is_dir():
        paths = _collect_run_dir(path)
        if not paths:
            print(
                f"daydream summarize: no trajectory.json or trajectories/ found under {path}",
                file=sys.stderr,
            )
            return 1
    else:
        print(
            f"daydream summarize: path is not a file or directory: {path}",
            file=sys.stderr,
        )
        return 1

    output = render_run_info_block(paths)
    print(output)

    # Renderer fell back because every input failed to parse — surface a
    # non-zero exit so callers know they didn't get a real summary.
    if _FALLBACK_NOTE in output:
        return 2
    return 0


def _collect_run_dir(run_dir: Path) -> list[Path]:
    """Collect ``trajectory.json`` plus any ``trajectories/*.json`` siblings."""
    paths: list[Path] = []
    parent = run_dir / "trajectory.json"
    if parent.is_file():
        paths.append(parent)
    siblings_dir = run_dir / "trajectories"
    if siblings_dir.is_dir():
        for sibling in sorted(siblings_dir.glob("*.json")):
            if sibling.is_file():
                paths.append(sibling)
    return paths


__all__ = ["summarize"]
