name: Bug Report
description: Report unexpected behavior or errors in Daydream
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug. Please provide as much context as possible to help us understand and reproduce the issue.

  - type: textarea
    id: goal
    attributes:
      label: What were you trying to accomplish?
      description: Describe the task or goal you were working on when you encountered this bug. What was the broader context?
      placeholder: "I was trying to run an automated code review on a Python project using the CLI..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe the behavior you expected based on your understanding of how Daydream should work.
      placeholder: "I expected the review agent to analyze my code and output actionable feedback..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: Describe what occurred instead. Include any error messages, unexpected outputs, or behaviors.
      placeholder: "The command hung during the review phase and then exited with an error..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide the exact steps to reproduce this behavior. Be as specific as possible.
      placeholder: |
        1. Clone a repo with Python code
        2. Run `daydream /path/to/project --python`
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Environment and configuration
      description: Include relevant details about your setup.
      placeholder: |
        - OS: macOS 14.2
        - Python: 3.12.1
        - Claude Code version: x.x.x
        - Beagle plugin version: x.x.x
        - Command used: daydream /path --python --debug
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: What have you tried?
      description: List any troubleshooting steps you've already attempted or workarounds you've found.
      placeholder: |
        - Tried with --debug flag to see more output
        - Tried with --review-only to isolate the issue
        - Checked if Beagle skills are installed
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact and frequency
      description: How does this bug affect your workflow? How often does it occur? Are there any patterns?
      placeholder: |
        This blocks my ability to run automated reviews entirely.
        It happens consistently on projects with more than 100 files.
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part of Daydream is affected?
      options:
        - CLI (argument parsing, entry point)
        - Runner (orchestration)
        - Review phase
        - Parse feedback phase
        - Fix phase
        - Test and heal phase
        - Agent SDK integration
        - UI (terminal output)
        - Beagle skills integration
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or output
      description: Include any relevant log output, stack traces, or command output. Use code blocks for formatting.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information that might be helpful. Screenshots, related issues, or observations about when this started occurring.
    validations:
      required: false
